In [1]:
import numpy as np
from numpy import ndarray as Matrix


def matprod(A : Matrix, B : Matrix) -> Matrix:
    n, ma = 0,0
    mb, p = 0,0

    if isinstance(A.shape, tuple):
        n, ma = A.shape
    elif isinstance(A.shape, int):
        n = A.shape / A[0].shape
        ma = n
    if isinstance(B.shape, tuple):
        mb, p = B.shape
    elif isinstance(B.shape, int):
        p = B.shape / B[0].shape
        mb = p

    if ma != mb:
        raise ValueError('dimension mismatch between A and B')
    
    C = np.zeros((n,p))
    
    for i in range(n):
        for j in range(p):
            for k in range(ma):
                C[i][j] += A[i][k] * B[k][j]
    return C

A = np.array([[-2, 5, 1], [0, 8, -7], [9, -4, -3], ])
B = np.array([[3, -4, 6,], [-5, 2, -1,], [8, -9, 0,]])

print(A@B)
print(matprod(A,B))

[[-23   9 -17]
 [-96  79  -8]
 [ 23 -17  58]]
[[-23.   9. -17.]
 [-96.  79.  -8.]
 [ 23. -17.  58.]]
