In [2]:
from polynomial import Polynomial

import matplotlib.pyplot as plt
import numpy as np

c = [2.0, 1.0, 1.0]
p = Polynomial(c)

x = np.eye(3)
print(p(x))
print(2*x + x + x**2)
# plt.plot(x, y, label=p.latex_string())
# plt.legend()
# plt.show()

[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]
[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]
